name: martincalvino
favicon: null
layout_spectrum: 0.75264
typography_spectrum: 0.09902597428299487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
  brandStrength: 0
  lightness: 0
  saturation: 0.0178603557869792
  rhythmicContrast: 0
purpose: []
